### ISSUE TITLE
Run selection spaces in file path problem

### ISSUE THREAD

**Issue by ngharrison** [apommel/vscode-matlab-interactive-terminal#11]
This is a nifty extension. I wouldn't have thought of using Python to run Matlab from within VS Code. I just tried it out and had one issue. If I "Run current selection in Matlab" with nothing selected it runs the current line, which is great. But if I "Run current selection in Matlab" with anything selected I get:

```
>> run("c:\Users\username\.vscode\extensions\apommel.matlab-interactive-terminal-0.3.1\temp\temp.m")

Error using cd
Too many input arguments.

Error in run (line 91)
evalin('caller', strcat(script, ';'));
```

It looks like it can't handle file paths with spaces, though only when running selected code. Running the same thing in a path with no spaces works.

**Comment by apommel** [comment]
Hello! Thanks a lot for your helpful feedback! This should be corrected now in the latest release that just went live. I close this issue.
