### ISSUE TITLE
Is it possible to add a prompt symbol like >>?

### ISSUE THREAD

**Issue by flcong** [apommel/vscode-matlab-interactive-terminal#2]
Thank you very much for the extension. I'm not sure if I did everything correct. When I launch the terminal, there is no prompt symbol there (e.g. >> in MATLAB).
![image](https://user-images.githubusercontent.com/37801658/73943132-39dd1e00-48be-11ea-9aab-fe10e504b9db.png)

**Comment by apommel** [comment]
I didn't think about that, I'll see what I can do !

**Comment by apommel** [comment]
I released a new version which should add these symbols, tell me if there's any problem with it!

**Comment by flcong** [comment]
Thank you very much! It works well.
