### ISSUE TITLE
Adding "Cursor Back to Editor" function for "Run Current Selection"

### ISSUE THREAD

**Issue by weihongliang233** [apommel/vscode-matlab-interactive-terminal#23]
Every time I use the "run current selection", the cursor goes to the terminal. When I need to continue coding, I have to point to the text manually. I suggest to make it optional. I made some modification to your code and now users can determine whether to make the cursor go back to its original position or just stay in the terminal.
When setting the "matlab-interactive-terminal.CursorBack" to true, it looks like:
![true](https://gitee.com/wei_hong_liang/My_Picture_Bed/raw/master/20201010233921.gif)

As shown in the gif, the cursor stays in the text.

When setting the "matlab-interactive-terminal.CursorBack" to false, it looks like:
![false](https://gitee.com/wei_hong_liang/My_Picture_Bed/raw/master/20201010234551.gif)

The cursor goes to the terminal.
Changing the configuration does't need a restart to take effect.

**Comment by weihongliang233** [comment]
A pull request has been created.
https://github.com/apommel/vscode-matlab-interactive-terminal/pull/24

**Comment by apommel** [comment]
Fixed with #24
