### ISSUE TITLE
runMatlabSelection doesn't work with arrays defined in multiple lines (Windows)

### ISSUE THREAD

**Issue by agutieda** [apommel/vscode-matlab-interactive-terminal#3]
- VSCode Version: 1.42.1
- Matlab Version: 2019b
- OS Version: Windows 10

Highlighting an array defined in several lines and using runMatlabSelection throws an error. As an example, running the following lines works in the Matlab editor but not with the interactive terminal in vscode:
```
A = [
    1, 2
    3, 4
    ];
```
I suspect this may have something to due with the lack of bracketed paste mode for the Windows terminal.

**Comment by apommel** [comment]
Hello, indeed this is due to the fact that when a selection is run, every line is processed independently. The easy solution would be to save the selection in a temporary file (it is already done this way when no terminal are opened). I will try to think about what would be best.

**Comment by apommel** [comment]
This is fixed in the latest release by using temporary files. It is not a 100% satisfactory solution so I may think about a redesign of the extension to solve this issue, along with a few others, more efficiently.

**Comment by agutieda** [comment]
Thank you!
