### ISSUE TITLE
Add to New Terminal menu

### ISSUE THREAD

**Issue by SNDST00M** [apommel/vscode-matlab-interactive-terminal#33]
Doesn't appear in the New Terminal menu for some reason.

<img src="https://user-images.githubusercontent.com/82655227/118046357-20543d00-b371-11eb-9912-b7a19d5a269a.png" width="515">

Is there a way to register the REPL as a VSC terminal?

**Comment by apommel** [comment]
I believe it is a completely different feature to implement. May be doable though.

**Comment by 4086606** [comment]
It's doable with https://github.com/microsoft/vscode-extension-samples/pull/449/ ! 😄
