### ISSUE TITLE
Automate the installation process

### ISSUE THREAD

**Issue by 4086606** [apommel/vscode-matlab-interactive-terminal#36]
We add an extension command that runs a shell script. What installation steps and checks would we do here?

**Comment by apommel** [comment]
You mean automating the MATLAB Engine installation ? I think the biggest issue with this would be that on a typical MATLAB/Python installation, admin rights are required to install the engine, on Windows at least.

**Comment by 4086606** [comment]
Would a Matlab script do the trick?

**Comment by 4086606** [comment]
Perhaps a Powershell script for Windows only? And sudo for Unix?

**Comment by apommel** [comment]
In any case it would require elevated privilege, and I don't feel a VS Code extension should ask for that. The installation process is sadly not straightforward, but I did not receive any complaints about it, so I guess it is fine as it is now.

**Comment by 4086606** [comment]
Sure, such a script would fail review even though it would be useful
