### ISSUE TITLE
Its not letting me enter inputs 

### ISSUE THREAD

**Issue by Abs-30** [apommel/vscode-matlab-interactive-terminal#43]

**Comment by somso2e** [comment]
This seems to be not supported by the MATLAB Python API itself and I doubt much can be done about it. Except maybe giving an error to the user when any of these commands are used?? https://in.mathworks.com/help/matlab/matlab_external/user-input-not-supported.html

**Comment by 7vik03** [comment]
@somso2e So, is that why once the MATLAB terminal takes my input, it just gets stuck and doesn't give me any output?

**Comment by Abs-30** [comment]
> This seems to be not supported by the MATLAB Python API itself and I doubt much can be done about it.
> 
> Except maybe giving an error to the user when any of these commands are used??
> 
> https://in.mathworks.com/help/matlab/matlab_external/user-input-not-supported.html

Thats the issue😊👍

**Comment by apommel** [comment]
Unfortunately, yes, not much can be done as the extension depends on the MATLAB Engine for Python. Implementing an error on the keyword sounds doable at first, but it would actually require to implement some kind of basic syntax parsing at the extension level for it to work reliably. It is not something I built the code for so I'd rather not delve into it.
I can only advise you to not use input and other similar functions.

**Comment by 7vik03** [comment]
@apommel Got it.
