### ISSUE TITLE
Outputs are displayed all at once when the program is completely over.

### ISSUE THREAD

**Issue by somso2e** [apommel/vscode-matlab-interactive-terminal#44]
Here's an example:
```
for j = 1:10
    fprintf("%d\n",j);
    pause(1)
end
```
The expected behavior is numbers being displayed one by one with a 1-second delay. But what ends up happening is all of them are displayed at once after 10 seconds.

system config:
Matlab Interactive Terminal v0.4.0
Python 3.8.0 64-bit
MATLAB R2020b

**Comment by apommel** [comment]
It is a well-known behavior (see #9). Try turning off "Unicode Switch" in the settings, and you should be able to see real-time output. Obviously, you will then be unable to see unicode characters in MATLAB output.
