### ISSUE TITLE
"Run current selection in Matlab" fails executing selection

### ISSUE THREAD

**Issue by juandarias** [apommel/vscode-matlab-interactive-terminal#45]
**SYSTEM**
Matlab R2021b
Ubuntu 20.04
VS Code 1.63

**Issue**
The command `Run current selection in MATLAB`, doesn't execute selection in MATLAB, but instead runs the following lines:
`>> clear("/home/xxx/.vscode-server/extensions/apommel.matlab-interactive-terminal-0.4.0/temp/temp.m")`
`>> run("/home/xxx/.vscode-server/extensions/apommel.matlab-interactive-terminal-0.4.0/temp/temp.m")`

**Comment by apommel** [comment]
To run the selection, a temporary MATLAB file containing the selected text is generated and executed. This is in order to avoid some issues with multi-line inputs.
Doesn't this work as expected?

**Comment by juandarias** [comment]
That is working fine. I will close the issues! Thank you
