### ISSUE TITLE
">>" symbol location error

### ISSUE THREAD

**Issue by ilcpm** [apommel/vscode-matlab-interactive-terminal#6]
when write 
```
fprintf('123abc')
```
in a `test.m` file and run
the result is
```
>> clear functions
>> run("d:\Code\matlab\test.m")
123abc>> 
```
the `>>` symbol should be placed into a new line

---
maybe to add a '\n' before '>>' after finish running a .m file?

**Comment by apommel** [comment]
This is corrected in the latest commit, sorry for the delay. It is not on the marketplace yet however.
