### ISSUE TITLE
Cannot use relative path names in code that is run from selection

### ISSUE THREAD

**Issue by jonniedie** [apommel/vscode-matlab-interactive-terminal#8]
Since "Run current selection in Matlab" creates a file in a temp directory and runs it from there, using relative path names doesn't work. This is an issue if your code needs to, say, read in data from a text file in its directory. There should be a ```cd(code_directory_name)``` call before the temp.m file is run.

**Comment by apommel** [comment]
Hello, thanks for your feedback!
I have put up a fix in the latest release (0.2.11), could you tell me if everything works correctly for you now?

**Comment by jonniedie** [comment]
Yep, it looks like it works. Thanks!
